export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const REGISTER_POST = 'REGISTER_POST';
export const CATEGORY_GET = 'CATEGORY_GET';

export const SET_MESSAGE = 'SET_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';

export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const ALL_CATEGORIES = 'ALL_CATEGORIES';
export const FIND_CATEGORY = 'FIND_CATEGORY';
export const UPDATE_CATEGORT = 'UPDATE_CATEGORT';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';

export const RECENT_POST = 'RECENT_POST';

export const USER_GET = 'USER_GET';
export const USER_UPDATE = 'USER_UPDATE';
export const IMAGE_UPDATE = 'IMAGE_UPDATE';

export const GET_POST = 'GET_POST';